"""all the const related to SF """

opportunity_schema_dict = {
    "id": "varchar",
    "is_deleted": "tinyint",
    "account_id": "varchar",
    "name": "text",
    "description": "text",
    "stage_name": "varchar",
    "amount": "double",
    "probability": "double",
    "close_date": "date",
    "type": "text",
    "next_step": "text",
    "lead_source": "text",
    "is_closed": "tinyint",
    "is_won": "tinyint",
    "forecast_category": "text",
    "forecast_category_name": "text",
    "campaign_id": "text",
    "has_opportunity_line_item": "tinyint",
    "pricebook_id": "double",
    "owner_id": "text",
    "created_date": "bigint",
    "created_by_id": "text",
    "last_modified_date": "bigint",
    "last_modified_by_id": "text",
    "system_modstamp": "bigint",
    "last_activity_date": "date",
    "last_stage_change_date": "double",
    "fiscal": "text",
    "contact_id": "text",
    "last_viewed_date": "bigint",
    "last_referenced_date": "bigint",
    "synced_quote_id": "double",
    "contract_id": "double",
    "has_open_activity": "tinyint",
    "has_overdue_task": "tinyint",
    "last_amount_changed_history_id": "varchar",
    "last_close_date_changed_history_id": "text",
    "Budget_Confirmed__c": "tinyint",
    "Discovery_Completed__c": "tinyint",
    "ROI_Analysis_Completed__c": "tinyint",
    "Loss_Reason__c": "text",
    "org_id": "int",
    "attributes_type": "text",
    "attributes_url": "text",
    "gn_user_id": "bigint",
    "created_date_utc": "datetime",
    "channel": "text",
    "last_modified_date_utc": "datetime",
    "record_type_id": "varchar",
    "formulaaaa__c": "mediumtext",
    "test__c": "mediumtext",
    "source": "text",
    "segment_type": "varchar",
    "is_flag": "tinyint",
}



lead_schema_dict = {
    "id": "varchar",
    "is_deleted": "tinyint",
    "master_record_id": "mediumtext",
    "name": "varchar",
    "title": "text",
    "company": "text",
    "phone": "varchar",
    "mobile_phone": "varchar",
    "email": "text",
    "website": "text",
    "photo_url": "text",
    "lead_source": "varchar",
    "status": "text",
    "industry": "varchar",
    "rating": "text",
    "number_of_employees": "mediumtext",
    "owner_id": "varchar",
    "is_converted": "tinyint",
    "converted_date": "text",
    "converted_account_id": "mediumtext",
    "converted_contact_id": "mediumtext",
    "converted_opportunity_id": "varchar",
    "is_unread_by_owner": "tinyint",
    "created_date": "bigint",
    "created_by_id": "text",
    "last_modified_date": "bigint",
    "last_modified_by_id": "text",
    "system_modstamp": "bigint",
    "last_activity_date": "varchar",
    "last_viewed_date": "text",
    "last_referenced_date": "mediumtext",
    "jigsaw": "mediumtext",
    "jigsaw_contact_id": "mediumtext",
    "email_bounced_reason": "mediumtext",
    "email_bounced_date": "mediumtext",
    "lead_status_2__c": "mediumtext",
    "org_id": "bigint",
    "attributes_type": "text",
    "attributes_url": "text",
    "domain": "varchar",
    "last_modified_date_utc": "timestamp",
    "created_date_utc": "timestamp",
    "channel": "text",
    "source": "text",
    "type": "mediumtext",
    "geocode_accuracy": "text",
    "segment_type": "varchar",
    "is_flag": "tinyint",
}




account_schema_dict = {
    "id": "varchar",
    "is_deleted": "tinyint",
    "master_record_id": "double",
    "type": "text",
    "parent_id": "text",
    "phone": "varchar",
    "website": "text",
    "photo_url": "text",
    "lead_source": "text",
    "industry": "text",
    "number_of_employees": "int",
    "description": "text",
    "owner_id": "text",
    "created_date": "bigint",
    "created_by_id": "text",
    "last_modified_date": "bigint",
    "last_modified_by_id": "text",
    "system_modstamp": "bigint",
    "last_activity_date": "text",
    "last_viewed_date": "bigint",
    "last_referenced_date": "bigint",
    "jigsaw": "int",
    "jigsaw_company_id": "double",
    "account_source": "text",
    "sic_desc": "double",
    "name": "tinytext",
    "org_id": "bigint",
    "attributes_type": "text",
    "attributes_url": "text",
    "shipping_city": "text",
    "shipping_country": "text",
    "shipping_state": "text",
    "gn_user_id": "bigint",
    "created_date_utc": "datetime",
    "last_modified_date_utc": "datetime",
    "record_type_id": "varchar",
    "fax": "varchar",
    "segment_type": "varchar",
    "is_flag": "tinyint",
    "is_abm": "int",
}



contact_schema_dict = {
    "id": "varchar",
    "is_deleted": "int",
    "master_record_id": "mediumtext",
    "account_id": "mediumtext",
    "name": "mediumtext",
    "phone": "mediumtext",
    "mobile_phone": "text",
    "reports_to_id": "text",
    "email": "text",
    "title": "text",
    "department": "text",
    "owner_id": "text",
    "created_date": "bigint",
    "created_by_id": "text",
    "last_modified_date": "mediumtext",
    "last_modified_by_id": "text",
    "system_modstamp": "bigint",
    "last_activity_date": "text",
    "last_c_u_request_date": "text",
    "last_c_u_update_date": "text",
    "last_viewed_date": "mediumtext",
    "last_referenced_date": "mediumtext",
    "email_bounced_reason": "text",
    "email_bounced_date": "text",
    "is_email_bounced": "bigint",
    "photo_url": "text",
    "lead_source": "text",
    "jigsaw": "text",
    "jigsaw_contact_id": "text",
    "Service_Offered__c": "text",
    "org_id": "bigint",
    "attributes_type": "text",
    "attributes_url": "text",
    "gn_user_id": "bigint",
    "domain": "text",
    "created_date_utc": "datetime",
    "last_modified_date_utc": "datetime",
    "fax": "mediumtext",
    "segment_type": "varchar",
    "is_flag": "tinyint",
}


